version: '3'
services:
  neo4j:
    container_name: neo4jnosql
    image: neo4j
    volumes:
      - ${NEO4JNOSQL_DATA}:/data \
    ports:
      - ${NEO4J_PORT_7474}:7474
      - ${NEO4J_PORT_7687}:7687
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    networks:
      - backend
networks:
  backend:
    driver: bridge
    