server:
  port: 9001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:postgresql://localhost:54321/todoList
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update